import discord
from discord.ext import commands
import asyncio
import datetime

bot = commands.Bot(command_prefix='.', case_insensitive=True)

@bot.event
async def on_ready():
    print('Ich bin Online')
    return await bot.change_presence(activity=discord.Activity(type=1, name='EinfachNurMaciej', url='https://twitch.tv/einfachnurmaciej'))



@bot.command(aliases=['p','info'])
async def profil(ctx):
    cl = ctx.author.colour
    embed = discord.Embed(colour=cl)
    embed.set_author(name=ctx.author, icon_url=ctx.author.avatar_url)
    embed.set_image(url=ctx.author.avatar_url)
    embed.add_field(name='Erstellt am:', value=ctx.author.created_at.__format__('%d.%m.%Y -- %H:%M:%S'))
    await ctx.send(embed=embed)

bot.run("Njk3NTM1MTIyNzE0Mzk0NzI0.Xo8HCQ.o6MuOfkCEdKnHkWFCSsRafNu5B8")